- name: Create a httpd service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: httpd-svc
        namespace: workloads
      spec:
        selector:
          app: httpd
        ports:
          - name: httpd-port
            protocol: TCP
            port: 80
            targetPort: 80

- name: Create a httpd route
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Route
      apiVersion: route.openshift.io/v1
      metadata:
        name: httpd-route
        namespace: workloads
      spec:
        to:
          kind: Service
          name: httpd-svc
          weight: 100
        port:
          targetPort: 80
        wildcardPolicy: None
