- hosts: namespace_ansible_managed_vm
  become: true  # Run tasks with root privileges
  tasks:
    - name: Install httpd package
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes  
