---
- name: Install common packages and httpd on RHEL-based systems
  hosts: namespace_ansible_managed_vm
  become: true
  gather_facts: true

  tasks:
    - name: Ensure we are on a RedHat-based system
      fail:
        msg: "Dieses Playbook ist nur für RedHat-basierte Systeme vorgesehen."
      when: ansible_os_family != 'RedHat'

    - name: Install common packages
      package:
        name:
          - curl
          - htop
          - tree
          - podman
          - vim
          - git
        state: present

    - name: Install httpd package
      package:
        name: httpd
        state: present

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
