- name: Apache Webserver configuration on OpenShift 
  hosts: namespace_workloads
  become: true
  collections:
    - redhat.openshift.k8s

  tasks:

    - name: Update all packages (RHEL)
      yum:
        name: '*'
        state: latest

    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Ensure httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
            <title>Automatisiert mit Ansible!</title>
            <style>
              body { font-family: Arial, sans-serif; background-color: #f4f4f9; color: #333; text-align: center; margin-top: 50px; }
              h1 { color: #336699; }
              p { font-size: 1.1em; line-height: 1.6em; }
              .footer { margin-top: 40px; font-size: 0.9em; color: #666; }
              img { margin-top: 30px; max-width: 100%; height: auto; }
            </style>
          </head>
          <body>
            <h1>Herzlich Willkommen!</h1>
            <p>Diese Webseite wurde vollautomatisch mit Ansible aufgesetzt.</p>
            <p>Mit einem Klick hat Ansible dafür gesorgt, dass Sie jetzt hier sind. Willkommen in der Welt der DevOps-Automatisierung!</p>

            <img src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fgursimarsm.medium.com%2Fopenshift-case-study-7082865402d1&psig=AOvVaw2a69fQhDTw7DZ9odjg-mIf&ust=1754558706918000&source=images&cd=vfe&opi=89978449&ved=0CBUQjRxqFwoTCMiuotju9Y4DFQAAAAAdAAAAABAE" alt="Simply Easy Learning" width="800" height="400">

            <div class="footer">
              <p>Server administriert durch Ansible | Erstellt am {{ ansible_date_time.date }}</p>
            </div>
          </body>
          </html>
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
